#!/bin/bash

### BEGIN INIT INFO
# Provides:       nginx
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

NAME=nginx

case $1 in
        start)
                # start php-fpm
                service php5-fpm start

                # start nginx
                nginx
                ;;
        stop)
                # stop php-fpm
                service php5-fpm stop 
                ;;

        *)
                echo "Usage: $NAME {start}" >&2
                exit 3
                ;;
esac

:
